#!/bin/sh

MAILDIR=/var/mail
PATH=/bin:/usr/bin

# Check if a given username is in /etc/passwd 
# and the users shell is in /etc/shells
check_username()
{
    USERSHELL=`grep "^${1}:" /etc/passwd | cut -d: -f7`
    [ -n "$USERSHELL" ] || return 1
    grep -v '^#' /etc/shells | grep -q $USERSHELL
    return $?
}

if check_username $1 ; then
    # do file locking and touch a non-existing mbox-file with right owner
    cat ${2} >> ${MAILDIR}/${1}
else
    exit 1
fi
