#!/bin/sh
# mmta, a minimal mail transport agent
# Copyright: 2008-2013 Teemu Ikonen <tpikonen@gmail.com>
# License: GPLv3+

# complain $MESSAGE
# Print and log a string
complain ()
{
    logger -t mmta $1
    echo $1 >&2
}

for USER in $(find /var/mail -type d -name *.mailq | sed 's,.*/\(.*\)\.mailq,\1,')
do
    /usr/lib/mmta/mmda send $USER || complain "$0: 'mmda send $USER' failed with exit code $?"
done

