#!/bin/sh
# mscript-helper action username param1 ...
# Perform an action with privileges of a given user

MAILDIR=/var/mail
PATH=/bin:/usr/bin

ACTION=$1 ; shift
USER=$1 ; shift 

if [ "$USER" = "root" ] ; then
    echo "$0: refusing to do anything as root" >&2
    exit 1
fi

# Check if a given username is in /etc/passwd 
# and the users shell is in /etc/shells
check_username()
{
    USERSHELL=`grep "^${1}:" /etc/passwd | cut -d: -f7`
    [ -n "$USERSHELL" ] || return 1
    grep -v '^#' /etc/shells | grep -q $USERSHELL
    return $?
}

if check_username $USER ; then
    true
else
    echo "$0: invalid user $USER" >&2
    exit 1
fi

case $ACTION in
    cat-mail)
        # do file locking and touch a non-existing mbox-file with right owner
        sudo -u $USER -- cat ${1} >> ${MAILDIR}/${USER}
        ;;
    *)
        echo "$0: invalid command $ACTION" >&2
        exit 1
        ;;
esac
