#!/bin/sh

MAILDIR="/var/mail/$(whoami).mailq"
HEADER="X-mmta-envelope-to:"

dotlockfile -p "$MAILDIR/lock"
for M in $(find $MAILDIR/new $MAILDIR/cur -type f) ; do
    RECIPIENTS=$(head -n 1 $M | sed -n "s/^$HEADER//p" | tr ',' ' ') 
    tail -n +2 $M | /usr/bin/msmtp -- $RECIPIENTS
    dotlockfile -t "$MAILDIR/lock"
    rm -f $M
done
dotlockfile -u "$MAILDIR/lock"
