#!/bin/sh
# Script to send messages from a mailqueue via msmtp through ssh tunnel
# Copyright: 2011 Teemu Ikonen <tpikonen@gmail.com>
# License: GPLv3+

[ -x /usr/bin/msmtp ] || exit 1

MAILDIR="/var/mail/$(whoami).mailq"
HEADER="X-mmta-envelope-to:"

ssh -N -i $HOME/.ssh/id_rsa user@forward.com -L 11587:smtp.gmail.com:587 > /dev/null &
SSH_PID=$!
sleep 3
if [ -d /proc/$SSH_PID ]; then
    dotlockfile -p "$MAILDIR/lock" || exit 1
    for M in $(find $MAILDIR/new $MAILDIR/cur -type f) ; do
        RECIPIENTS=$(head -n 1 $M | sed -n "s/^$HEADER//p" | tr ',' ' ')
        if tail -n +2 $M | /usr/bin/msmtp -- $RECIPIENTS ; then
	    rm -f $M
        fi
        dotlockfile -t "$MAILDIR/lock"
    done
    dotlockfile -u "$MAILDIR/lock"
    kill $SSH_PID
fi
