#!/bin/sh
# Script to check if msmtp can send mail
# Copyright: 2008-2017 Teemu Ikonen <tpikonen@gmail.com>
# License: GPLv3+

scriptname=$0
verbose=0

die () {
    [ "$verbose" = "1" ] || exit $1
    logger -t mmta "$scriptname: $2"
    exit $1
}

SPOOLDIR=/var/spool/mmta
QUEUEDIR="${SPOOLDIR}/$(whoami)"
[ -x /usr/bin/msmtp ] || die 1 "/usr/bin/msmtp does not exist."
[ -r "$HOME/.msmtprc" ] || die 1 "$HOME/.msmtprc is not readable."
[ -d "$QUEUEDIR" ] || die 1 "Maildir $QUEUEDIR does not exist."

echo "" | /usr/bin/msmtp -P 2>&1 > /dev/null
