#!/bin/sh
# Script to send messages from a mailqueue via msmtp
# Copyright: 2008 Teemu Ikonen <tpikonen@gmail.com>
# License: GPLv3+

[ -x /usr/bin/msmtp ] || exit 1

MAILDIR="/var/mail/$(whoami).mailq"
HEADER="X-mmta-envelope-to:"

HOST=$(sed -n 's/^host\s\s*\(.*\)/\1/p' $HOME/.msmtprc)
ping -c 1 -w 2 $HOST > /dev/null 2>&1 || exit 0

dotlockfile -p "$MAILDIR/lock" || exit 1
for M in $(find $MAILDIR/new $MAILDIR/cur -type f) ; do
    RECIPIENTS=$(head -n 1 $M | sed -n "s/^$HEADER//p" | tr ',' ' ') 
    if tail -n +2 $M | /usr/bin/msmtp -- $RECIPIENTS ; then
	rm -f $M
    fi
    dotlockfile -t "$MAILDIR/lock"
done
dotlockfile -u "$MAILDIR/lock"
