#!/bin/sh
# Script to add a message to mail queue
# Copyright: 2008 Teemu Ikonen <tpikonen@gmail.com>
# License: GPLv3+

[ -x /usr/bin/msmtp ] || exit 1
MAILDIR="/var/mail/$(whoami).mailq"
[ -d "$MAILDIR" ] || exit 1
MTMP="$MAILDIR/tmp"
MNEW="$MAILDIR/new"
HEADER="X-mmta-envelope-to:"

mkdir $MTMP
mkdir $MNEW
mkdir "$MAILDIR/cur"

(echo -n "$HEADER "
echo -n "$1" ; shift
while R=$1 ; shift ; do echo -n ", ${R}" ; done ; echo
cat) | /usr/bin/safecat $MTMP $MNEW > /dev/null 2>&1
