#!/bin/sh
# Script to check if msmtp can send mail
# Copyright: 2008-2013 Teemu Ikonen <tpikonen@gmail.com>
# License: GPLv3+

scriptname=$0

die () {
    logger -t mmta $scriptname: $2
    exit $1
}

MAILDIR="/var/mail/$(whoami).mailq"
[ -x /usr/bin/msmtp ] || die 1 "/usr/bin/msmtp does not exist."
[ -r $HOME/.msmtprc ] || die 1 "$HOME/.msmtprc is not readable."
[ -d $MAILDIR ] || die 1 "Maildir $MAILDIR does not exist."

echo "" | /usr/bin/msmtp -P 2>&1 > /dev/null
