#!/bin/sh
# Script to check if msmtp can send mail
# Copyright: 2008-2013 Teemu Ikonen <tpikonen@gmail.com>
# License: GPLv3+

scriptname=$0

die () {
    logger -t mmta $scriptname: $2
    exit $1
}

MAILDIR="/var/mail/$(whoami).mailq"
[ -x /usr/bin/msmtp ] || die 1 "/usr/bin/msmtp does not exist."
[ -r $HOME/.msmtprc ] || exit 1
[ -d $MAILDIR ] || exit 1

/usr/bin/msmtp -P > /dev/null 2>&1
