#!/bin/sh
# Script to get msmtp password from the user.
# Copyright: 2008-2013 Teemu Ikonen <tpikonen@gmail.com>
# License: GPLv3+

# Ask for the msmtp password for the users mail account, which is parsed
# from ~/.msmtprc.
# Subjects for mails to be sent are shown.
# If no password is given, the dialog times out, so that unattended mode
# fails gracefully.

TIMEOUT=60

MAILDIR="/var/mail/$(whoami).mailq"
headers=$(grep -r '^Subject:' $MAILDIR)
account=$(sed -n 's/^from \(.*\)/\1/p' $HOME/.msmtprc)

if [ "$DISPLAY" ]
then
    pw=$(zenity --entry \
--title="Enter msmtp password" \
--text="msmtp wants to send these mails:\n\n$headers\n\nEnter password for ${account}:" \
--timeout=$TIMEOUT \
--hide-text)
else
    # If no X display, fail.
    pw=""
fi

echo $pw
